# An Ansible playbook that installs a Minecraft server
- name: Make sure package manager is up to date
  hosts: all
  become: yes

  tasks:
    - name: Install Java
      ansible.builtin.package:
        name:
          - openjdk-21-jre-headless
        state: latest

    - name: Make service account
      ansible.builtin.user:
        name: svc_minecraft
        create_home: false
        password: '*'
        shell: '/usr/bin/false'
        system: true

    - name: Create Server Folder
      ansible.builtin.file:
        state: "directory"
        path: '/opt/minecraft/server'
        owner: svc_minecraft

    - name: Download Minecraft Server
      ansible.builtin.get_url:
        url: 'https://piston-data.mojang.com/v1/objects/145ff0858209bcfc164859ba735d4199aafa1eea/server.jar'
        dest: '/opt/minecraft/server/server.jar'
        owner: svc_minecraft
    - name: Initialize Minecraft Server Directory
      ansible.builtin.shell:
        cmd: "java -jar /opt/minecraft/server/server.jar"

    - name: Accept EULA
      ansible.builtin.copy:
        content: "eula=true"
        dest: "/opt/minecraft/server/eula.txt"
        owner: svc_minecraft

    - name: Create Minecraft Start Script
      ansible.builtin.copy:
        src: "files/start.sh"
        dest: "/opt/minecraft/server/start.sh"
        owner: svc_minecraft
        mode: "0550"

    - name: Create Minecraft Stop Script
      ansible.builtin.copy:
        src: "files/stop.sh"
        dest: "/opt/minecraft/server/stop.sh"
        owner: svc_minecraft
        mode: "0550"

    - name: Create Minecraft Service File
      ansible.builtin.copy:
        src: "files/minecraft.service"
        dest: "/etc/systemd/system/minecraft.service"
        owner: root
        group: root
        mode: "0644"

    - name: Enable Minecraft Service
      ansible.builtin.systemd_service:
        name: minecraft
        enabled: true
        masked: no

    - name: Start Minecraft Service
      ansible.builtin.systemd_service:
        name: minecraft
        state: started
